services:
  corax-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corax_crypto_engine
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8000"
    volumes:
      # Mountar koden för live-utveckling
      - .:/app
      # Skyddar containerns installerade bibliotek från att döljas av din lokala mapp
      - /app/.venv
      # Mappar data, loggar och config till din OS-disk
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config